### ISSUE TITLE
章节奇数页排版看这里

### ISSUE THREAD

**Issue by melyseengit** [sqyx008/BUPTBachelorThesis#12]
### 修改文件**main.tex**
![screenshot from 2018-05-21 10-29-57](https://user-images.githubusercontent.com/26475063/40287748-22ae7ea0-5ce2-11e8-9b28-d5e63632d2bd.png)
将红框处原来的**oneside**修改为**openright**

### renew ： hold
修改后出现一点小问题，暂时保留意见。解决后更新这里。

在正文前**中英文摘要**之间的空白页左上角出现了不受欢迎的小数字。
![screenshot from 2018-05-21 10-48-55](https://user-images.githubusercontent.com/26475063/40288202-9828535c-5ce4-11e8-81aa-8314e85e748e.png)

- 任何评论、问题、解决方法都是受欢迎的，请发布comment。

**Comment by sheng-qiang** [comment]
看了一下《指导手册》，发现没有对奇数页排版的要求，这样改是出于什么考虑？

**Comment by melyseengit** [comment]
感谢回复！
我没看指导手册，这个是做毕设的组的要求，所以在这里提出了。如果指导手册没有这个要求，请忽略这条issue所提出的修改。

**Comment by sheng-qiang** [comment]
中英文摘要页上不受欢迎的小数字已经消除，记得更新abstract.tex
@JoyBeginner

**Comment by melyseengit** [comment]
感谢回复！
完全更新后，摘要之间消除了小数字，但是诚信声明后的空白页左上角出现小数字。
