### ISSUE TITLE
mac中文显示问题

### ISSUE THREAD

**Issue by tingtingliangvs** [sqyx008/BUPTBachelorThesis#15]
正常情况是把texshop：偏好设置里的编码改成UTF-8就好，但如果你的ctex宏包未安装或未更新，texshop编辑器的中文显示依然为乱码。
解决办法是重新安装ctex宏包。如果你的tex live也出了问题，可以重新安装tex live，注意要与tex shop版本一致。
当然我是删除了原来的2017版mactex，重新安装了mactex2018，并更新所有软件包。

**Comment by xtyDoge** [comment]
发现字体是华文宋体，华文黑体和华文楷体，应如何修改？
