### ISSUE TITLE
Mac平台字体错误

### ISSUE THREAD

**Issue by xtyDoge** [sqyx008/BUPTBachelorThesis#17]
Mac平台下，编译出的pdf中宋体、楷体、黑体等字体分别变成了华文宋体、华文楷体与华文黑体

**Comment by sheng-qiang** [comment]
可以尝试#9中的解决方案，字体可能会因为平台更换而变化。

**Comment by xtyDoge** [comment]
已解决

打开`/usr/local/texlive/2016/texmf-dist/tex/latex/ctex/fontset/ctex-xecjk-mac.def`文件（目录可能与安装的mactex版本有关），将其中的`STSong`，`STHei`和`STKaiti`对应修改为`SimSun`，`SimHei`与`KaiTi`即可，或者打开font Book.app自行寻找对应字体的PostScript名称进行替换

**Comment by NarcissusInMirror** [comment]
@xtyDoge 感谢！
在MacTex2018配置文件为`ctex-fontset-mac.def`，路径为`/usr/local/texlive/2018/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-mac.def`，将文件中全部的`STSong`,`STHei`,`STKaiti`修改为`SimSun`,`SimHei`,`KaiTi`即可。
