### ISSUE TITLE
外文文献排版问题

### ISSUE THREAD

**Issue by xtyDoge** [sqyx008/BUPTBachelorThesis#18]
指导书上说格式参照论文正文。是仍需要用正文的chapter，section标签来排英文文献中的 I II III 和 A B C吗

**Comment by sheng-qiang** [comment]
建议直接按照正文格式，但不要使用\section等指令，直接用\section等的样式配置”伪造“一下即可

**Comment by xtyDoge** [comment]
一头雾水……可否将相应代码整合至模板的例子中？感谢

**Comment by sheng-qiang** [comment]
@xtyDoge 我已经给了一个简单的例子，请pull最新的commit
