### ISSUE TITLE
参考文献 “et al” “等”

### ISSUE THREAD

**Issue by CptGit** [sqyx008/BUPTBachelorThesis#19]
真的可以用“et al”吗，指导手册里是“等”？

**Comment by sheng-qiang** [comment]
我记得手册写的是，英文使用et al，中文用等。

中文要切换成“等”，需要在.bib中加入language＝{Chinese}

**Comment by CptGit** [comment]
可是，我没有在手册里发现et al字样……

**Comment by sheng-qiang** [comment]
我也没有发现...但我打算就这么保留了，因为我觉得这应归因于教务考虑不周，等它challenge我再说。

在英文参考中加汉字太匪夷所思了。

**Comment by CptGit** [comment]
其实我依然不是很懂，为啥中文论文的参考文献要用英文写……感觉这样也挺违和。

**Comment by sheng-qiang** [comment]
@CptGit 参考的完全是英文文献，自然要用英文叙述，这一点参照其它中文期刊。
