### ISSUE TITLE
参考文献 论文集格式与指导手册有巨大出入

### ISSUE THREAD

**Issue by CptGit** [sqyx008/BUPTBachelorThesis#20]
1. 指导手册要求“见/In”后有句点“.”，而目前格式无；
2. 大量句点变为逗号；
3. 主编位置不对。
bst不会改。。。求救……

附，可以发现出入之大：
指导手册要求：
[序号] 作者.论文题目.见(英文用In).主编.论文集名.出版地.出版年:页码范围.

按当前bst生成的一篇参考文献：
[3] Buro Michael. Real-time Strategy Gaines: A New AI Research Challenge [C] // editorname. In Proceedings of the 18th International Joint Conference on Artificial Intelligence, San Francisco, CA, USA, 2003:1534–1535.

**Comment by sheng-qiang** [comment]
把你附的这篇IJCAI使用的bibTeX一块发上来对照一下

**Comment by CptGit** [comment]
bib:
```
@inproceedings{Buro03real-timestrategy,
    author = {Buro, Michael},
    title = {Real-time Strategy Games: A New AI Research Challenge},
    booktitle = {Proceedings of the 18th International Joint Conference on Artificial Intelligence},
    year = {2003},
    location = {Acapulco, Mexico},
    pages = {1534--1535},
    numpages = {2},
    publisher = {Morgan Kaufmann Publishers Inc.},
    address = {San Francisco, CA, USA},
    editor = {Unknown},
}
```

pdf:
`Buro Michael. Real-time Strategy Games: A New AI Research Challenge [C] // Unknown. In Proceedings of the 18th International Joint Conference on Artificial Intelligence, San Francisco, CA, USA, 2003: 1534–1535.`

**Comment by sheng-qiang** [comment]
标点问题已经修正；
“见”和“In”的切换已经修正；
由于其诡异性，抛弃“主编”字段。
