### ISSUE TITLE
Ubuntu 16.04 XeLaTex编译没有章节号

### ISSUE THREAD

**Issue by melyseengit** [sqyx008/BUPTBachelorThesis#23]
舍友在win下编译是有章节号的，这个问题匪夷所思，目前没有找到解决方法。

PS：答辩的同学一定要**注意格式**。

**Comment by sheng-qiang** [comment]
查一下main.log 看一下章节号输出的地方有没有warning出现

**Comment by melyseengit** [comment]
solved.


下载**titlesec**包解压到/usr/share/texlive/texmf-dist/tex/latex

下载链接：https://www.ctan.org/tex-archive/macros/latex/contrib/titlesec
