### ISSUE TITLE
附录中的代码如何也设置出”附-代码-XX“的效果？

### ISSUE THREAD

**Issue by Ncerzzk** [sqyx008/BUPTBachelorThesis#24]
rt，目前附录中的代码编号还是沿用上一章的编号。

在.sty中找了半天，没找到lstlisting的编号写在哪里，求助~

**Comment by sheng-qiang** [comment]
@Ncerzzk 刚才调整了一下，最新的commit中已经实现了“代码 附-1”的样式风格，另外顺便补充了直接引用代码文件来显示代码的示例。

**Comment by Ncerzzk** [comment]
谢谢！已解决！
