### ISSUE TITLE
参考文献段落间距

### ISSUE THREAD

**Issue by moonhwi** [sqyx008/BUPTBachelorThesis#26]
今天答辩老师说参考文献不可以加段落间距，参考文献看着的确间距好大。

**Comment by sheng-qiang** [comment]
解决方案请尝试http://blog.sina.com.cn/s/blog_5e16f1770100ldv5.html。
参考文献的间距是相关宏包的默认设置，考虑到论文格式检查以教务处《指导手册》为准，且经过查看其中没有针对参考文献部分的间距规定，故模板中不会进行更新。
虽然答辩老师可以指出着一些建议，但他们没有权利在《指导手册》规定之外加入强制性要求。
