### ISSUE TITLE
chapter标题与参考文献标题上下间距

### ISSUE THREAD

**Issue by Sean10** [sqyx008/BUPTBachelorThesis#27]
在修改titlespacing上下间距均为0后，发现章节标题上方依旧有留白，下方没有了留白，而参考文献下方却出现了一块留白区域。

请问参考文献的那块空白区域哪里可以修改呢？

---------

发现这块空白区域是由于\centerline导致的，去掉这个之后依旧水平居中，并且没有了下方空白，所以满足了我的需求。

**Comment by xtyDoge** [comment]
请问章节标题上方的留白是指导手册要求的吗？会影响纸质版论文的检查吗

**Comment by sheng-qiang** [comment]
留白是LaTeX的典型设置，但不是指导手册的要求，指导手册没有相关的明确表述。
理论上讲法不禁止则允许，除非教务颐指气使...

**Comment by Sean10** [comment]
@xtyDoge 指导手册并没有要求，只是当时我指导老师希望看着和Word制作的接近一些。我前几天去交时，看到其他的一份LaTex生成了，应该没有修改这部分留白，也通过了。所以就像sqyx008说的，并不是必需要求，只是个人稍稍修改一下。
