### ISSUE TITLE
修改摘要的关键词不应该首行缩进问题

### ISSUE THREAD

**Issue by lebronlambert** [sqyx008/BUPTBachelorThesis#28]
改成这样就行  \par\noindent 加上这个 \par针对当前段落  \noindent 取消首行缩进

\input{abstract.cfg}

% 中文摘要
\begin{titlepage}
    \begin{spacing}{1.05}
        \centering
        \parbox[c]{.6\textwidth}{\thesistitlefont{\thesistitle}}
    \end{spacing}

    \begin{spacing}{1.6}
        \centering
        \sanhao\quad{} \\ 
        \abszhname{摘\quad{}要} \\ 
        \xiaosanhao\quad{}
    \end{spacing}
    
    \normalsize

    \abstractcn
    
    \quad{}
    
\par\noindent\abszhkey{关键词}\quad{}%
\abszhkeys{\abscnkeyone\quad{}%
                      \abscnkeytwo\quad{}%
                      \abscnkeythree\quad{}%
                      \abscnkeyfour\quad{}%
                      \abscnkeyfive}%
\end{titlepage}

% Abstract
\begin{titlepage}
    \begin{spacing}{1.05}
        \centering
        \parbox[c]{.6\textwidth}{\thesistitleenfont{\thesistitleen}}
    \end{spacing}

    \begin{spacing}{1.6}
        \centering
        \sanhao\quad{} \\ 
        \abszhname{ABSTRACT} \\ 
        \xiaosanhao\quad{}
    \end{spacing}

    \normalsize

    \abstracten
    
    \quad{}
    
\par\noindent\absenkey{KEY WORDS}\quad{}%
    \absenkeys{\absenkeyone\quad{}%
                      \absenkeytwo\quad{}%
                      \absenkeythree\quad{}%
                      \absenkeyfour\quad{}%
                      \absenkeyfive}%
\end{titlepage}

**Comment by sheng-qiang** [comment]
关键词不进行首行缩进未在《指导手册》上发现。

**Comment by lebronlambert** [comment]
Negative 我们班说了要求这个

**Comment by sheng-qiang** [comment]
@lebronlambert 确认一下信源的可靠性。

**Comment by melyseengit** [comment]
根据今天发下的论文修改意见，已确认要求关键字不缩进。

**Comment by sheng-qiang** [comment]
@JoyBeginner 我昨天在现场，负责我班的检查小组成员亲自询问了寿心灵老师，得到了指导手册上没有规定，两种都可以接受的答复。
