### ISSUE TITLE
请问如何在参考文献里添加对维基百科、开源项目的引用啊？

### ISSUE THREAD

**Issue by ZanderChang** [sqyx008/BUPTBachelorThesis#3]
在看以前的论文发现有的标了[Z/OL]，有的什么也没标

**Comment by sheng-qiang** [comment]
像维基百科这样的，可以直接使用[EB/OL]，仿照示例在.bib写就好了；
开源项目如果是学术研究衍生的，一般作者会希望你直接引用该项目对应的论文，找到论文的bibTeX即可，如果是无对应论文的工程项目，一般使用脚注（\footnote）写下GitHub地址即可，或者也可以仿照采用[EB/OL]

**Comment by ZanderChang** [comment]
好的我知道了，谢谢！
