### ISSUE TITLE
今天检查被指出的问题

### ISSUE THREAD

**Issue by xtyDoge** [sqyx008/BUPTBachelorThesis#30]
~~1. 摘要关键词一行不应该缩进~~
2. 目录的点点的不对（？？？）
3. chapter标题距页眉空间过大

4. 页边距太大，量着接近3cm了
5. 参考文献行距过大
6. ‘外文译文'四个字不加粗

4，5两条比较致命

**Comment by sheng-qiang** [comment]
1.没有规定；
2.检察人员吹毛求疵罢了，它们对格式有极致追求，却没有合理的基础知识作为支撑；
3.正文的要求只包含行间距、字体字号样式，其它如留白空间不属于规定范畴；
4.边距是严格准确的，检查人员无法证明这不是打印时的缩放造成的；
5.行距也为1.2倍，条目之间的间隔没有进行要求；
6.不加粗已经更新在最新的commit上；

我今天跟踪了全天的格式检查，其中有很多吹毛求疵的点。本模板的仍然坚持，《指导手册》中没有明确写明的都不应增加额外规定，给予自由排版的合理空间，法不禁止则允许。

另外的建议是，班里的人不能软绵绵的，要擅长**怼**。

**Comment by xtyDoge** [comment]
@sqyx008 
没有去参与现场的格式检查，这些点都是班里的同学回来告诉我的。
其中第2点他都觉得好笑，还有第3点我的问题是第三章和第五章的标题有问题，其他的没有。
第4点的页边距，我测量了一下我的纸质版论文，发现右间距在2.8cm左右，可能是我使用的版本太老，可否提供一下打印地点？

至于最后说吹毛求疵的事，想到了《套中人》里的几句话，相比法无禁止则允许，我觉得这些话更能反映这次格式检查的哲学，毕竟宁可请这么多人也不愿意给出官方模板：

>只有政府的告示和报纸上的文章，其中规定着禁上什么，他才觉得一清二楚。看到有个告示禁止中学学生在晚上九点钟以后到街上去，他就觉得又清楚又明白：这种事是禁止的，好，这就行了。

吐槽归吐槽，然而无法通过检查的话，感觉模板就失去了存在的意义

**Comment by sheng-qiang** [comment]
第4点我量了一些word模板的论文，发现也做不到2.5cm，所以推测是打印的问题。

这不是吐槽，而是据理力争。比如第一点，本来他们都是按照这个标准去查的，但昨天早上询问过信通院教务科科长寿心灵老师后，得到了“顶格与否都可以”的答复；另外，昨天检查同学要求中期检查表的检查小组意见不能“太简单”，但同学在找其对应的检查小组组长吴建伟老师时，吴老师向寿老师确认后，认为“通过”两个字足矣。

检查人员在搞不清楚时，倾向于严苛，因为这样他们不犯错。想要不陷入这种糟糕的境况，参考《指导手册》，最最起码参考成文之前就已经存在的“准确补充通知”，才是最好的操作方案。

**Comment by sheng-qiang** [comment]
@xtyDoge 我已经更改了参考文献的间距，请参照最新的commit。
