### ISSUE TITLE
目录、页码问题

### ISSUE THREAD

**Issue by melyseengit** [sqyx008/BUPTBachelorThesis#31]
检查反馈：
- 目录的点和word不一样（这条我打算无视）
- 页码位置太靠上（这条蓝皮书上位置只指定了居中）
    - 修改BUPTthesisbachelor.sty文件footskip。我设置的1，不知道和word是否一致，看起来还行
- 参考文献间距
    - 在bbl文件增加\addtolength{\itemsep}{-1em}。这个也是，我设置的-1em，看起来还行

两个参数大家酌情设置

**Comment by sheng-qiang** [comment]
1.第一个可以无视，我在现场看到很多检查人员不会在意这一点。
2.估计是正文比较靠下的原因；
3.间距这个也是取决于人，有一些人比较死。

**Comment by sheng-qiang** [comment]
@JoyBeginner 参考文献部分我给出了一种针对natbib包的改法，请参照最新的commit。如果你更改bbl文件的话，重新编译时会被覆盖吧。
