### ISSUE TITLE
6.21下午审查新出现的问题

### ISSUE THREAD

**Issue by VladimirDuan** [sqyx008/BUPTBachelorThesis#32]
+ 参考文献要两端对齐。（？？？）
+ 外文翻译要求每章另起新页。 

我本人就先不改了，继续观望吧，明天可能又出现新规定。

**Comment by sheng-qiang** [comment]
1.参考文献一般没有这种问题，你使用URL的话，为了保证链接完整，会换行书写；
2.这个你可以使用\newpage，当然……也可以怼。
