### ISSUE TITLE
pdf格式知网查重会有问题吗？

### ISSUE THREAD

**Issue by theYuan** [sqyx008/BUPTBachelorThesis#34]
观此贴有感：https://bbs.byr.cn/#!article/Paper/34014?p=1
也看到了一些解决办法：https://www.cnblogs.com/yuehq/p/6700911.html

**Comment by sheng-qiang** [comment]
我去年是将PDF转word后，又做了少量整理再提交知网查重的。

**Comment by theYuan** [comment]
好的，感谢~
