### ISSUE TITLE
目录两页页码大小不一致

### ISSUE THREAD

**Issue by GeorgeDong21** [sqyx008/BUPTBachelorThesis#38]
您好，我使用模版自动生成的目录，但是第一页目录和第二页目录下面自动生成的罗马数字页码大小不一样，且看起来一个加粗了一个没有加粗，请问怎么修改呢。

**Comment by sheng-qiang** [comment]
You may upload snapshots to help find the problem.

**Comment by GeorgeDong21** [comment]
<img width="1283" alt="屏幕快照 2019-06-11 下午12 32 01" src="https://user-images.githubusercontent.com/37075449/59243918-f950d600-8c44-11e9-9f06-c48c95096953.png">
我截了一张图，应该可以展示我的问题

**Comment by sheng-qiang** [comment]
针对你的问题，我刻意增长了main.pdf中的目录长度至第二页，发现它们都是正确字号且样式统一，我将重新上传该事例供你测试。但请注意，我没有对.sty做任何修改。

**Comment by happybyr** [comment]
确实有这个问题，目录第二页的页码小于第一页

**Comment by sheng-qiang** [comment]
请你尝试将引入目录的代码调换顺序，即
\fancypagestyle{plain}...在前
\frontmatter\tableofcontents...在后

**Comment by happybyr** [comment]
你看看目录的页码中，罗马字母1和罗马字母2的大小是否一样

**Comment by happybyr** [comment]
> 请你尝试将引入目录的代码调换顺序，即
> \fancypagestyle{plain}...在前
> \frontmatter\tableofcontents...在后
问题成功解决了，可以关闭ISSUE
