### ISSUE TITLE
查重时提交的是word还是pdf？如果需要提交word就不能用LaTex了，不是很清楚。

### ISSUE THREAD

**Issue by houjingyi233** [sqyx008/BUPTBachelorThesis#4]

**Comment by thinkwee** [comment]
可以提交pdf

**Comment by sheng-qiang** [comment]
1.知网查重系统接收PDF版本。
2.能不能用PDF版全凭你所在学院教务科有关人员的要求。据了解信通院是可以的，欢迎其它学院同学跟帖所在学院的要求。

**Comment by Ncerzzk** [comment]
自动化院交word，推荐使用Pandoc，可将tex直接转为word，公式居然可以直接识别，除了标签和引用识别不出来，可能要手动删一下。

https://github.com/jgm/pandoc/releases/tag/2.2.1
