### ISSUE TITLE
在章节标题后直接写正文，标题和正文间隔太近

### ISSUE THREAD

**Issue by cdxeve** [sqyx008/BUPTBachelorThesis#40]
在chapter{}后直接写正文，标题和正文间隔太近

1.pdf:
<img width="758" alt="截屏2020-04-04上午11 53 13" src="https://user-images.githubusercontent.com/26034310/78418020-e4797f00-766a-11ea-9ad4-7cf094dbda26.png">
2.代码：
<img width="495" alt="截屏2020-04-04上午11 53 59" src="https://user-images.githubusercontent.com/26034310/78418032-0115b700-766b-11ea-9b73-e97a4570a75e.png">

**Comment by jz8-armohb** [comment]
我也有这个问题，请问怎么解决呢

> 在chapter{}后直接写正文，标题和正文间隔太近
> 
> 1.pdf: <img alt="截屏2020-04-04上午11 53 13" width="758" src="https://user-images.githubusercontent.com/26034310/78418020-e4797f00-766a-11ea-9ad4-7cf094dbda26.png"> 2.代码： <img alt="截屏2020-04-04上午11 53 59" width="495" src="https://user-images.githubusercontent.com/26034310/78418032-0115b700-766b-11ea-9b73-e97a4570a75e.png">

**Comment by cdxeve** [comment]
@jz8-armohb 
你好，这个是我2020年提的issue我已经快忘了，我去看了当时的代码，在\chapter{xxx}后面加了两行这个：
\bigskip
\medskip
这之后再写你的文字就可以。

**Comment by jz8-armohb** [comment]
非常感谢！看起来很正常了（没想到这么快就回复了

**Comment by cdxeve** [comment]
@jz8-armohb 没事 祝你毕业顺利！
