### ISSUE TITLE
对BUPTthesisbachelor.sty的补充

### ISSUE THREAD

**Issue by SuZhiman** [sqyx008/BUPTBachelorThesis#6]
\usepackage{amsthm} %如果不加入这个包，在写proof环境的时候编译会出问题

\newtheorem{theorem}{定理}[chapter]  %定理没有定义

——————
email:chenziyi@bupt.edu.cn

**Comment by SuZhiman** [comment]
同时，好像引用(\ref)前面section章节的时候第一次编译会乱码，出现??的形式。第二次编译这种情况消失。

**Comment by sheng-qiang** [comment]
1. ??的形式是正常的，本来就需要两次编译。
2.  其它定义，已经添加。
