### ISSUE TITLE
关于分图的设置

### ISSUE THREAD

**Issue by DropNetL** [sqyx008/BUPTBachelorThesis#8]
指导手册关于图表的部分要求：
* 如果图中含有不同部分，应将分图序号标注在分图的左上角，并在图名下列出各分图图名。

请问这部分文档中有对应的实现方案吗？

**Comment by sheng-qiang** [comment]
因为我自己书写时没有用上，所以目前没有实现方案。你可以：
1.自己拼接一下，当一整个图放进去；
2.等我“面向搜索引擎编程”一下，不知道能不能实现到位……

如果有人已经实现了分图要求，欢迎提交pull request

**Comment by sheng-qiang** [comment]
我面向搜索引擎编程回来了，组图的示例已经上传，请对照main.tex和main.pdf查看熟悉。因为组图中子图的数量不同，不方便压缩成一个新的函数，目前就这么用吧。
